### ISSUE TITLE
Support for `/query`

### ISSUE THREAD

**Issue by neufeldtech** [swalberg/promproxy#3]
Would you consider adding support for the Prometheus `/query` endpoint?

This would allow us to use tables in Grafana with the `instant` checkbox enabled, whereas currently PromProxy only works with Grafana tables by displaying all of the datapoints in the returned time range, which is not ideal for all use-cases

**Comment by swalberg** [comment]
Hey Jordan I can look into this. If it's similar to the other APIs it should be fairly straightforward.
